import { execFileSync } from 'node:child_process';
import { mkdirSync, cpSync, writeFileSync, rmSync, symlinkSync, readFileSync } from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const version = JSON.parse(readFileSync('app/package.json')).version;
const release = path.join(root, 'release');
const staging = path.join(release, 'staging');
const bundle = path.join(staging, 'Stocknews.app');
const contents = path.join(bundle, 'Contents');
const resources = path.join(contents, 'Resources');
const run = (cmd, args, cwd = root) => execFileSync(cmd, args, { cwd, stdio: 'inherit' });
if (process.platform !== 'darwin' || process.arch !== 'arm64') throw new Error('Requires Apple Silicon macOS');
run('npm', ['run', 'build']);
rmSync(staging, { recursive: true, force: true });
mkdirSync(path.join(contents, 'MacOS'), { recursive: true });
mkdirSync(path.join(resources, 'runtime'), { recursive: true });
const app = path.join(resources, 'workspace/app');
mkdirSync(app, { recursive: true });
for (const dir of ['server', 'shared', 'dist/client']) cpSync(path.join(root, 'app', dir), path.join(app, dir), { recursive: true });
for (const file of ['package.json', 'package-lock.json']) cpSync(path.join(root, 'app', file), path.join(app, file));
run('npm', ['ci', '--omit=dev', '--ignore-scripts', '--no-audit', '--no-fund'], app);
run('lipo', [process.execPath, '-thin', 'arm64', '-output', path.join(resources, 'runtime/node')]);
run('chmod', ['755', path.join(resources, 'runtime/node')]);
run('swiftc', ['desktop/main.swift', '-O', '-target', 'arm64-apple-macosx13.0', '-framework', 'Cocoa', '-framework', 'WebKit', '-o', path.join(contents, 'MacOS/Stocknews')]);
writeFileSync(path.join(contents, 'Info.plist'), `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>
<key>CFBundleExecutable</key><string>Stocknews</string><key>CFBundleIdentifier</key><string>com.stocknews.desktop</string><key>CFBundleName</key><string>Stocknews</string><key>CFBundleDisplayName</key><string>Stocknews</string><key>CFBundlePackageType</key><string>APPL</string><key>CFBundleShortVersionString</key><string>${version}</string><key>CFBundleVersion</key><string>${version}</string><key>LSMinimumSystemVersion</key><string>13.0</string><key>NSHighResolutionCapable</key><true/><key>NSAppTransportSecurity</key><dict><key>NSAllowsLocalNetworking</key><true/></dict></dict></plist>`);
writeFileSync(path.join(resources, 'BUILD_COMMIT'), execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }));
run('codesign', ['--force', '--sign', '-', path.join(resources, 'runtime/node')]);
run('codesign', ['--force', '--deep', '--sign', '-', bundle]);
run('codesign', ['--verify', '--deep', '--strict', bundle]);
symlinkSync('/Applications', path.join(staging, 'Applications'));
writeFileSync(path.join(staging, '安装说明.txt'), '将 Stocknews.app 拖到 Applications。适用于 Apple Silicon，macOS 13 或更新版本。\n数据保存于 ~/Library/Application Support/Stocknews，不包含开发机器数据或账号授权。\n本包为本地测试版本，未经过 Apple 公证。\n');
const dmg = path.join(release, `Stocknews_${version}_arm64.dmg`);
run('hdiutil', ['create', '-volname', 'Stocknews', '-srcfolder', staging, '-ov', '-format', 'UDZO', dmg]);
run('shasum', ['-a', '256', dmg]);
console.log(dmg);
